### ISSUE TITLE
Minion implementation in java

### ISSUE THREAD

**Issue by lawrencelai** [bkimminich/kata-tcg#26]
Minion implementation in Java

**Comment by bkimminich** [comment]
I didn't provide a solution for Minions so far, because during my developer trainings I let the students do this on top of my otherwise feature-complete Java implementation.

I could add Minions and then use a separate branch like ´´´no-minions´´´ for my trainings, but that would still make cheating a lot more likely, if a sample implementation is just a ´´´git checkout master´´´ away... :-)
